name: ci

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: 'package.json'

      - run: pnpm i
      - run: pnpm run lint
      - run: pnpm run fmt-check
      - run: pnpm tsc
      # - run: pnpm run test-unit
